; This file was auto-generated by drush make
core = 7.x

api = 2
projects[drupal][version] = "7.50"

; Modules
projects[admin_menu][version] = "3.0-rc5"

projects[ctools][version] = "1.9"

projects[charts][version] = "2.0-rc1"

projects[node_clone][version] = "1.0"

projects[features][version] = "2.10"

projects[hybridauth][version] = "2.15"

projects[jquery_update][version] = "2.7"

projects[pathauto][version] = "1.3"

projects[publishcontent][version] = "1.4"

projects[qforms][version] = "1.0-beta1"

projects[qforms_extra][version] = "1.0-alpha1"

projects[simplified_social_share][version] = "4.1"

projects[token][version] = "1.6"

projects[views][version] = "3.14"

; Themes
projects[bootstrap][version] = "3.5"

; Modules
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[ubersurvey_blocks][download][type] = ""
projects[ubersurvey_blocks][download][url] = ""
projects[ubersurvey_blocks][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[ubersurvey_participants][download][type] = ""
projects[ubersurvey_participants][download][url] = ""
projects[ubersurvey_participants][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[ubersurvey_summary][download][type] = ""
projects[ubersurvey_summary][download][url] = ""
projects[ubersurvey_summary][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[ubersurvey_ui][download][type] = ""
projects[ubersurvey_ui][download][url] = ""
projects[ubersurvey_ui][type] = "module"

; Themes
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[ubersurvey][download][type] = ""
projects[ubersurvey][download][url] = ""
projects[ubersurvey][type] = "theme"

